name: jamendo_music_player
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.1
  flutter_riverpod: ^3.3.2
  http: ^1.6.0
  just_audio: ^0.10.6
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # flutter_launcher_icons: ^0.14.4

# flutter_launcher_icons: 
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icon/icon.png"
#   min_sdk_android: 21
#   adaptive_icon_foreground: "assets/icon/icon.png"
#   adaptive_icon_background: "#ffffff"
#   remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icon/
    - assets/animations/
